### ISSUE TITLE
pip requirements not up-to-date

### ISSUE THREAD

**Issue by thisisshub** [kbhutani0001/Certify#15]
I was just setting up this project and found out that `astroid==2.3.3` does not meet the current version requirement. 

**I get the following error when I run pip install -r requirements.txt**
`ERROR: Could not find a version that satisfies the requirement astroid==2.3.3 (from -r requirements.txt (line 1))`

**The current versions of astroid available are** 
`(from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6)`

I think we should change the `README.md` line 34.
for `pip install -r requirements.txt` with `pip3 install -r requirements.txt`

as `pip` uses python2 packages whereas we need `pip3`
Should I PR for this?

**Comment by kaybhutani** [comment]
Seems right. Go ahead make a PR
