### ISSUE TITLE
store verified images to database instead of file system

### ISSUE THREAD

**Issue by kaybhutani** [kbhutani0001/Certify#24]
We are currently using file system to store images which is not a good way. We need to store images to the data base too (the same being used for user details).
Prolly compress the images to a height of 500px that is being used everywhere and then store the encoded form

**Comment by grossamos** [comment]
Given that no one has been found to help with this issue so far, I'd very much enjoy working on it.

**Comment by kaybhutani** [comment]
@grossamos go ahead 👍

**Comment by grossamos** [comment]
Okay, pull request created 👌

**Comment by kaybhutani** [comment]
solved in #31
